import { User, Document, Message, Meeting, Payment, Agency } from './types';

export const mockUsers: User[] = [
  {
    id: 'super-admin-1',
    role: 'SUPER_ADMIN',
    fullName: 'Global Admin',
    email: 'akil@migratehub.com', // changed to akil as per instruction
    phone: '+1234567890',
    gender: 'Other',
    age: 40,
    dob: '1984-01-01',
    nationality: 'Global',
    address: 'HQ Street, NY',
    currentLivingCountry: 'USA',
    mailingAddress: 'HQ Street, NY',
    maritalStatus: 'Single',
    registrationDate: '2024-01-01',
    password: 'eternals', // adding a password field for mock auth
  },
  {
    id: 'admin-1',
    role: 'ADMIN',
    fullName: 'Sarah Johnson',
    email: 'sarah@visa-experts.com',
    phone: '+1234567891',
    gender: 'Female',
    age: 35,
    dob: '1989-05-15',
    nationality: 'USA',
    address: '123 Agency St, London',
    currentLivingCountry: 'UK',
    mailingAddress: '123 Agency St, London',
    maritalStatus: 'Married',
    registrationDate: '2024-01-05',
    agencyId: 'agency-1',
    agencyName: 'Visa Experts Ltd',
  },
  {
    id: 'agent-1',
    role: 'AGENT',
    fullName: 'David Smith',
    email: 'david@visa-experts.com',
    phone: '+1234567892',
    gender: 'Male',
    age: 30,
    dob: '1994-08-20',
    nationality: 'UK',
    address: '456 Agent Rd, Manchester',
    currentLivingCountry: 'UK',
    mailingAddress: '456 Agent Rd, Manchester',
    maritalStatus: 'Single',
    registrationDate: '2024-01-10',
    agencyId: 'agency-1',
    agencyName: 'Visa Experts Ltd',
    licenseNumber: 'MARA-998877',
    countriesSupported: ['Australia', 'Canada', 'UK'],
    visasSupported: ['Student Visa', 'Skilled Work Visa', 'PR'],
    languagesSpoken: ['English', 'Spanish'],
    yearsExperience: 7,
    bio: 'Specialist in Australian and Canadian migration pathways with 7+ years of experience.',
    rating: 4.8,
    successRate: 95,
    availability: [
      { day: 'Monday', slots: ['09:00', '10:00', '14:00', '15:00'] },
      { day: 'Wednesday', slots: ['10:00', '11:00', '16:00'] },
    ]
  },
  {
    id: 'agent-2',
    role: 'AGENT',
    fullName: 'Elena Rodriguez',
    email: 'elena@visa-experts.com',
    phone: '+1234567893',
    gender: 'Female',
    age: 32,
    dob: '1992-11-12',
    nationality: 'Spain',
    address: '789 Vista Way, Madrid',
    currentLivingCountry: 'Spain',
    mailingAddress: '789 Vista Way, Madrid',
    maritalStatus: 'Married',
    registrationDate: '2024-01-12',
    agencyId: 'agency-1',
    agencyName: 'Visa Experts Ltd',
    licenseNumber: 'MARA-112233',
    countriesSupported: ['Spain', 'Germany', 'USA'],
    visasSupported: ['Student Visa', 'Business Visa', 'Digital Nomad'],
    languagesSpoken: ['Spanish', 'English', 'German'],
    yearsExperience: 5,
    bio: 'Helping professionals and students move to Europe and the USA.',
    rating: 4.9,
    successRate: 92,
    availability: [
      { day: 'Tuesday', slots: ['09:00', '11:00'] },
      { day: 'Thursday', slots: ['14:00', '15:00', '17:00'] },
    ]
  },
  {
    id: 'user-1',
    role: 'USER',
    fullName: 'Alex Chen',
    email: 'alex@example.com',
    phone: '+1234567894',
    gender: 'Male',
    age: 24,
    dob: '2000-03-25',
    nationality: 'China',
    address: 'Beijing, China',
    currentLivingCountry: 'China',
    mailingAddress: 'Beijing, China',
    maritalStatus: 'Single',
    registrationDate: '2024-02-01',
    targetCountry: 'Australia',
    visaType: 'Student Visa',
    educationLevel: 'Bachelor Degree',
    englishScore: 'IELTS 7.5',
    passportNumber: 'E12345678',
    applicationStatus: 'DOCUMENT_COLLECTION',
    assignedAgentId: 'agent-1',
  },
  {
    id: 'user-2',
    role: 'USER',
    fullName: 'Maria Garcia',
    email: 'maria@example.com',
    phone: '+1234567895',
    gender: 'Female',
    age: 28,
    dob: '1996-07-10',
    nationality: 'Mexico',
    address: 'Mexico City, Mexico',
    currentLivingCountry: 'Mexico',
    mailingAddress: 'Mexico City, Mexico',
    maritalStatus: 'Single',
    registrationDate: '2024-02-05',
    targetCountry: 'Canada',
    visaType: 'Skilled Work Visa',
    educationLevel: 'Master Degree',
    englishScore: 'PTE 79',
    passportNumber: 'G98765432',
    applicationStatus: 'REGISTRATION',
    requestedAgentId: 'agent-1', // Pending approval
  },
  {
    id: 'user-3',
    role: 'USER',
    fullName: 'Lucas Muller',
    email: 'lucas@example.com',
    phone: '+49123456789',
    gender: 'Male',
    age: 26,
    dob: '1998-05-15',
    nationality: 'Germany',
    address: 'Berlin, Germany',
    currentLivingCountry: 'Germany',
    mailingAddress: 'Berlin, Germany',
    maritalStatus: 'Single',
    registrationDate: '2024-02-10',
    targetCountry: 'USA',
    visaType: 'Business Visa',
    educationLevel: 'Bachelor',
    englishScore: 'TOEFL 100',
    passportNumber: 'P11223344',
    applicationStatus: 'REGISTRATION',
    assignedAgentId: 'agent-2', // Assigned but not yet accepted by agent
  }
];

export const mockAgencies: Agency[] = [
  {
    id: 'agency-1',
    name: 'Visa Experts Ltd',
    ownerId: 'admin-1',
    subscriptionPlan: 'PRO',
    revenue: 15000,
    totalClients: 45,
    totalAgents: 5,
    status: 'ACTIVE',
    joinedAt: '2024-01-01T00:00:00Z',
    email: 'contact@visa-experts.com',
    contactNumber: '+44 20 7123 4567',
    address: '123 Agency St, London, UK',
    licenseNumber: 'LIC-2024-EXPERTS',
  }
];

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    userId: 'user-1',
    uploadedById: 'user-1',
    name: 'Passport_Alex.pdf',
    category: 'PASSPORT',
    status: 'APPROVED',
    uploadedAt: '2024-02-02T10:00:00Z',
    fileUrl: '#',
    fileType: 'pdf',
  },
  {
    id: 'doc-2',
    userId: 'user-1',
    uploadedById: 'user-1',
    name: 'Academic_Transcript.pdf',
    category: 'ACADEMIC',
    status: 'UNDER_REVIEW',
    uploadedAt: '2024-02-03T11:30:00Z',
    fileUrl: '#',
    fileType: 'pdf',
  }
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    senderId: 'agent-1',
    receiverId: 'user-1',
    content: 'Hi Alex, I have reviewed your passport. It looks good!',
    timestamp: '2024-02-02T14:00:00Z',
    isRead: true,
  },
  {
    id: 'msg-2',
    senderId: 'user-1',
    receiverId: 'agent-1',
    content: 'Thanks David! I am uploading my transcripts now.',
    timestamp: '2024-02-02T14:05:00Z',
    isRead: true,
  }
];

export const mockMeetings: Meeting[] = [
  {
    id: 'meet-1',
    agentId: 'agent-1',
    userId: 'user-1',
    title: 'Initial Consultation',
    type: 'ZOOM',
    startTime: '2024-02-15T10:00:00Z',
    duration: 30,
    link: 'https://zoom.us/j/123456789',
    status: 'ACCEPTED',
  }
];

export const mockPayments: Payment[] = [
  {
    id: 'pay-1',
    userId: 'user-1',
    amount: 500,
    currency: 'USD',
    status: 'PAID',
    description: 'Initial Consultation Fee',
    date: '2024-02-01T09:00:00Z',
    method: 'STRIPE',
  }
];
